// Generated by CoffeeScript 1.10.0
var blocks, clearTimer, degValue, re, test, timer;

blocks = [];

test = 0;

degValue = 0;

re = true;

timer = 0;

$(document).on("ready", function() {
  test = new TetriminoRed;
  return timer = setInterval((function() {
    re = test.move(30, 0);
    console.log("re: " + re);
    if (re === false) {
      return clearInterval(timer);
    }
  }), 1000);
});

$(window).on("keydown", function(e) {
  if (test !== "wait") {
    if (e.keyCode === 40) {
      test.move(30, 0);
      return clearTimer();
    } else if (e.keyCode === 39) {
      test.move(0, 30);
      return clearTimer();
    } else if (e.keyCode === 37) {
      test.move(0, -30);
      return clearTimer();
    } else if (e.keyCode === 32) {
      if (degValue < 270) {
        test.rotate(degValue += 90);
      } else {
        test.rotate(0);
        degValue = 0;
      }
      return clearTimer();
    }
  }
});

clearTimer = function() {
  if (re === false) {
    return clearInterval(timer);
  }
};
